# Generated by Django 5.2.9 on 2026-02-15 18:14

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_message_reactions_message_reply_to'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='message',
            name='removed_by',
            field=models.ManyToManyField(blank=True, related_name='removed_messages', to=settings.AUTH_USER_MODEL),
        ),
    ]
