# Generated by Django 5.2.9 on 2026-04-03 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0005_message_call_duration_message_message_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='call_started_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
