# Generated by Django 5.2.9 on 2026-02-17 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning', '0002_learningsession_actual_end_time_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='learningsession',
            name='is_paused',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='learningsession',
            name='paused_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='learningsession',
            name='remaining_duration_seconds',
            field=models.IntegerField(blank=True, help_text='Remaining seconds when paused', null=True),
        ),
    ]
