# Generated by Django 5.2.9 on 2026-03-03 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning', '0003_learningsession_is_paused_learningsession_paused_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='learningsession',
            name='admin_confirmed',
            field=models.BooleanField(default=False, help_text='Has the admin confirmed session completion?'),
        ),
        migrations.AddField(
            model_name='learningsession',
            name='is_paid',
            field=models.BooleanField(default=False, help_text='Has the student paid the session fee?'),
        ),
        migrations.AddField(
            model_name='learningsession',
            name='payout_completed',
            field=models.BooleanField(default=False, help_text='Has the teacher received the payment?'),
        ),
    ]
