# Generated by Django 5.2.9 on 2026-03-03 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning', '0004_learningsession_admin_confirmed_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='learningsession',
            name='is_free',
            field=models.BooleanField(default=False, help_text='Is this a free session?'),
        ),
    ]
