# Generated by Django 5.2.9 on 2026-03-04 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning', '0005_learningsession_is_free'),
    ]

    operations = [
        migrations.AddField(
            model_name='learningsession',
            name='total_price',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Total price for the session including platform fee', max_digits=10),
        ),
    ]
