# Generated by Django 5.2.9 on 2026-04-03 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning', '0006_learningsession_total_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='learningsession',
            name='status',
            field=models.CharField(choices=[('SCHEDULED', 'Scheduled'), ('ONGOING', 'Ongoing'), ('COMPLETED', 'Completed'), ('CANCELLED', 'Cancelled'), ('WITHDRAWN', 'Withdrawn'), ('EXPIRED', 'Expired')], default='SCHEDULED', max_length=20),
        ),
        migrations.AlterField(
            model_name='sessionrequest',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('ACCEPTED', 'Accepted'), ('REJECTED', 'Rejected'), ('CANCELLED', 'Cancelled'), ('WITHDRAWN', 'Withdrawn'), ('EXPIRED', 'Expired'), ('COMPLETED', 'Completed')], default='PENDING', max_length=20),
        ),
    ]
