# Generated by Django 5.2.9 on 2026-04-08 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning', '0008_learningsession_reschedule_reason_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sessionrequest',
            name='proposed_time',
            field=models.DateTimeField(blank=True, help_text='Optional proposed meeting time', null=True),
        ),
    ]
