# Generated by Django 5.2.9 on 2026-04-09 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning', '0009_sessionrequest_proposed_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sessionrequest',
            name='proposed_time',
            field=models.DateTimeField(blank=True, help_text='Optional proposed meeting time by the requester', null=True),
        ),
    ]
