# Generated by Django 5.2.9 on 2026-01-15 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='availability',
            field=models.TextField(blank=True, help_text='Comma-separated list of available times'),
        ),
    ]
