# Generated by Django 5.2.9 on 2026-04-06 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0003_transaction_payment_method_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='order_id',
            field=models.CharField(blank=True, help_text='Generic Internal Order ID', max_length=255, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='khalti_purchase_order_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
