# Generated by Django 5.2.9 on 2026-02-20 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_userprofile_availability'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='sessions_learned_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='sessions_taught_count',
            field=models.IntegerField(default=0),
        ),
    ]
