# Generated by Django 5.2.9 on 2026-03-04 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_userprofile_sessions_learned_count_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='hourly_rate',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Hourly rate in NPR', max_digits=10),
        ),
    ]
