# Generated by Django 5.2.9 on 2026-04-05 02:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_userprofile_email_notifications_enabled_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='is_onboarded',
            field=models.BooleanField(default=False),
        ),
    ]
