# Generated by Django 5.2.9 on 2026-04-09 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_userprofile_is_onboarded'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='rating',
            field=models.FloatField(default=0.0, help_text='Average teacher rating from student feedback'),
        ),
    ]
